import { relations, sql } from "drizzle-orm";
import { check, index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const audit = { createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()) };
const id = () => text("id").primaryKey();

export const cities = sqliteTable("cities", { id: id(), name: text("name").notNull(), countryCode: text("country_code").notNull().default("MA"), latitude: real("latitude").notNull(), longitude: real("longitude").notNull(), googlePlaceId: text("google_place_id").unique(), ...audit }, t => [index("cities_name_idx").on(t.name), index("cities_country_idx").on(t.countryCode)]);
export const user = sqliteTable("user", { id: id(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: integer("email_verified", { mode: "boolean" }).notNull().default(false), phoneNumber: text("phone_number").unique(), phoneNumberVerified: integer("phone_number_verified", { mode: "boolean" }).notNull().default(false), image: text("image"), dateOfBirth: integer("date_of_birth", { mode: "timestamp_ms" }), role: text("role", { enum: ["user", "admin", "superadmin"] }).notNull().default("user"), banned: integer("banned", { mode: "boolean" }).notNull().default(false), banReason: text("ban_reason"), banExpires: integer("ban_expires", { mode: "timestamp_ms" }), cityId: text("city_id").references(() => cities.id, { onDelete: "set null" }), profilePhotoStepCompleted: integer("profile_photo_step_completed", { mode: "boolean" }).notNull().default(false), notificationPermissionAsked: integer("notification_permission_asked", { mode: "boolean" }).notNull().default(false), onboardingCompleted: integer("onboarding_completed", { mode: "boolean" }).notNull().default(false), deletedAt: integer("deleted_at", { mode: "timestamp_ms" }), ...audit }, t => [index("user_city_idx").on(t.cityId), index("user_name_idx").on(t.name), index("user_deleted_idx").on(t.deletedAt)]);
export const session = sqliteTable("session", { id: id(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), token: text("token").notNull().unique(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), impersonatedBy: text("impersonated_by"), ...audit }, t => [index("session_user_idx").on(t.userId), index("session_expires_idx").on(t.expiresAt)]);
export const account = sqliteTable("account", { id: id(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: integer("access_token_expires_at", { mode: "timestamp_ms" }), refreshTokenExpiresAt: integer("refresh_token_expires_at", { mode: "timestamp_ms" }), scope: text("scope"), password: text("password"), ...audit }, t => [uniqueIndex("account_provider_account_uidx").on(t.providerId, t.accountId), index("account_user_idx").on(t.userId)]);
export const verification = sqliteTable("verification", { id: id(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), ...audit }, t => [index("verification_identifier_idx").on(t.identifier), index("verification_expires_idx").on(t.expiresAt)]);

export const clubs = sqliteTable("clubs", { id: id(), cityId: text("city_id").notNull().references(() => cities.id, { onDelete: "restrict" }), name: text("name").notNull(), address: text("address").notNull(), latitude: real("latitude").notNull(), longitude: real("longitude").notNull(), phone: text("phone"), image: text("image"), googlePlaceId: text("google_place_id").unique(), ...audit }, t => [index("clubs_city_idx").on(t.cityId), index("clubs_name_idx").on(t.name)]);
export const gameFormats = sqliteTable("game_formats", { id: id(), name: text("name").notNull().unique(), playersPerTeam: integer("players_per_team").notNull(), maxPlayers: integer("max_players").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), ...audit }, t => [check("format_capacity_check", sql`${t.playersPerTeam} > 0 and ${t.maxPlayers} >= ${t.playersPerTeam} * 2`)]);
export const games = sqliteTable("games", { id: id(), hostId: text("host_id").notNull().references(() => user.id, { onDelete: "restrict" }), clubId: text("club_id").notNull().references(() => clubs.id, { onDelete: "restrict" }), formatId: text("format_id").notNull().references(() => gameFormats.id, { onDelete: "restrict" }), date: integer("date", { mode: "timestamp_ms" }).notNull(), price: integer("price").notNull().default(0), currency: text("currency").notNull().default("MAD"), status: text("status", { enum: ["draft", "scheduled", "confirmed", "completed", "cancelled"] }).notNull().default("draft"), visibility: text("visibility", { enum: ["public", "friends", "private", "circles"] }).notNull().default("public"), joinableAt: integer("joinable_at", { mode: "timestamp_ms" }), invitationCode: text("invitation_code").notNull().unique(), cancellationReason: text("cancellation_reason"), ...audit }, t => [index("games_host_idx").on(t.hostId), index("games_club_idx").on(t.clubId), index("games_format_idx").on(t.formatId), index("games_date_idx").on(t.date), index("games_status_idx").on(t.status), index("games_visibility_idx").on(t.visibility), check("games_price_check", sql`${t.price} >= 0`)]);
export const gamePlayers = sqliteTable("game_players", { id: id(), gameId: text("game_id").notNull().references(() => games.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => user.id, { onDelete: "restrict" }), invitedById: text("invited_by_id").references(() => user.id, { onDelete: "set null" }), status: text("status", { enum: ["invited", "accepted", "waiting", "declined", "removed", "left"] }).notNull(), source: text("source", { enum: ["host", "invitation", "link", "discovery", "circle"] }).notNull(), isHost: integer("is_host", { mode: "boolean" }).notNull().default(false), joinedAt: integer("joined_at", { mode: "timestamp_ms" }), ...audit }, t => [uniqueIndex("game_players_game_user_uidx").on(t.gameId, t.userId), index("game_players_game_idx").on(t.gameId), index("game_players_user_idx").on(t.userId), index("game_players_status_idx").on(t.status)]);
export const gameGuests = sqliteTable("game_guests", { id: id(), gameId: text("game_id").notNull().references(() => games.id, { onDelete: "cascade" }), sponsorId: text("sponsor_id").notNull().references(() => user.id, { onDelete: "restrict" }), name: text("name").notNull(), phone: text("phone"), status: text("status", { enum: ["invited", "accepted", "removed"] }).notNull().default("accepted"), ...audit }, t => [index("game_guests_game_idx").on(t.gameId), index("game_guests_sponsor_idx").on(t.sponsorId)]);

export const circles = sqliteTable("circles", { id: id(), ownerId: text("owner_id").notNull().references(() => user.id, { onDelete: "restrict" }), name: text("name").notNull(), description: text("description"), image: text("image"), privacy: text("privacy", { enum: ["public", "private"] }).notNull().default("private"), shareCode: text("share_code").notNull().unique(), archivedAt: integer("archived_at", { mode: "timestamp_ms" }), ...audit }, t => [index("circles_owner_idx").on(t.ownerId), index("circles_name_idx").on(t.name)]);
export const circleMembers = sqliteTable("circle_members", { id: id(), circleId: text("circle_id").notNull().references(() => circles.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => user.id, { onDelete: "restrict" }), role: text("role", { enum: ["owner", "admin", "member"] }).notNull().default("member"), status: text("status", { enum: ["invited", "requested", "accepted", "rejected", "removed"] }).notNull(), ...audit }, t => [uniqueIndex("circle_members_circle_user_uidx").on(t.circleId, t.userId), index("circle_members_user_idx").on(t.userId), index("circle_members_status_idx").on(t.status)]);
export const gameCircles = sqliteTable("game_circles", { id: id(), gameId: text("game_id").notNull().references(() => games.id, { onDelete: "cascade" }), circleId: text("circle_id").notNull().references(() => circles.id, { onDelete: "cascade" }), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()) }, t => [uniqueIndex("game_circles_game_circle_uidx").on(t.gameId, t.circleId), index("game_circles_circle_idx").on(t.circleId)]);

export const connectionRequests = sqliteTable("connection_requests", { id: id(), senderId: text("sender_id").notNull().references(() => user.id, { onDelete: "restrict" }), receiverId: text("receiver_id").notNull().references(() => user.id, { onDelete: "restrict" }), message: text("message"), status: text("status", { enum: ["pending", "accepted", "rejected", "cancelled"] }).notNull().default("pending"), ...audit }, t => [index("connection_requests_sender_idx").on(t.senderId), index("connection_requests_receiver_idx").on(t.receiverId), uniqueIndex("connection_requests_pending_pair_uidx").on(sql`min(${t.senderId}, ${t.receiverId})`, sql`max(${t.senderId}, ${t.receiverId})`).where(sql`${t.status} = 'pending'`), check("connection_requests_not_self_check", sql`${t.senderId} <> ${t.receiverId}`)]);
export const userConnections = sqliteTable("user_connections", { id: id(), userOneId: text("user_one_id").notNull().references(() => user.id, { onDelete: "restrict" }), userTwoId: text("user_two_id").notNull().references(() => user.id, { onDelete: "restrict" }), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()) }, t => [uniqueIndex("user_connections_pair_uidx").on(t.userOneId, t.userTwoId), index("user_connections_two_idx").on(t.userTwoId), check("user_connections_canonical_check", sql`${t.userOneId} < ${t.userTwoId}`)]);

export const notifications = sqliteTable("notifications", { id: id(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), type: text("type").notNull(), payload: text("payload", { mode: "json" }).notNull().$type<Record<string, unknown>>(), readAt: integer("read_at", { mode: "timestamp_ms" }), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()) }, t => [index("notifications_user_idx").on(t.userId), index("notifications_read_idx").on(t.readAt), index("notifications_created_idx").on(t.createdAt), index("notifications_inbox_idx").on(t.userId, t.readAt, t.createdAt)]);
export const notificationPreferences = sqliteTable("notification_preferences", { id: id(), userId: text("user_id").notNull().unique().references(() => user.id, { onDelete: "cascade" }), pushEnabled: integer("push_enabled", { mode: "boolean" }).notNull().default(true), gameInvitationsEnabled: integer("game_invitations_enabled", { mode: "boolean" }).notNull().default(true), gameRemindersEnabled: integer("game_reminders_enabled", { mode: "boolean" }).notNull().default(true), chatMessagesEnabled: integer("chat_messages_enabled", { mode: "boolean" }).notNull().default(true), circleUpdatesEnabled: integer("circle_updates_enabled", { mode: "boolean" }).notNull().default(true), marketingEnabled: integer("marketing_enabled", { mode: "boolean" }).notNull().default(false), ...audit });
export const notificationDevices = sqliteTable("notification_devices", { id: id(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), provider: text("provider").notNull(), subscriptionId: text("subscription_id").notNull().unique(), platform: text("platform", { enum: ["ios", "android"] }).notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }).notNull(), ...audit }, t => [index("notification_devices_user_idx").on(t.userId), index("notification_devices_active_idx").on(t.active)]);
export const badges = sqliteTable("badges", { id: id(), category: text("category").notNull(), threshold: integer("threshold").notNull(), name: text("name").notNull(), description: text("description").notNull(), icon: text("icon").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), ...audit }, t => [uniqueIndex("badges_category_threshold_uidx").on(t.category, t.threshold), index("badges_active_idx").on(t.active), check("badges_threshold_check", sql`${t.threshold} > 0`)]);
export const userBadges = sqliteTable("user_badges", { id: id(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), badgeId: text("badge_id").notNull().references(() => badges.id, { onDelete: "restrict" }), unlockedAt: integer("unlocked_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()) }, t => [uniqueIndex("user_badges_user_badge_uidx").on(t.userId, t.badgeId), index("user_badges_badge_idx").on(t.badgeId)]);
export const userTracking = sqliteTable("user_tracking", { id: id(), userId: text("user_id").notNull().unique().references(() => user.id, { onDelete: "cascade" }), gamesPlayed: integer("games_played").notNull().default(0), gamesHosted: integer("games_hosted").notNull().default(0), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()) }, t => [check("tracking_nonnegative_check", sql`${t.gamesPlayed} >= 0 and ${t.gamesHosted} >= 0`)]);

export const userRelations = relations(user, ({ one, many }) => ({ city: one(cities, { fields: [user.cityId], references: [cities.id] }), sessions: many(session), accounts: many(account), hostedGames: many(games, { relationName: "games_host" }), gameMemberships: many(gamePlayers, { relationName: "game_players_user" }), circles: many(circleMembers), notifications: many(notifications), badges: many(userBadges), tracking: one(userTracking) }));
export const sessionRelations = relations(session, ({ one }) => ({ user: one(user, { fields: [session.userId], references: [user.id] }) }));
export const accountRelations = relations(account, ({ one }) => ({ user: one(user, { fields: [account.userId], references: [user.id] }) }));
export const citiesRelations = relations(cities, ({ many }) => ({ users: many(user), clubs: many(clubs) }));
export const clubsRelations = relations(clubs, ({ one, many }) => ({ city: one(cities, { fields: [clubs.cityId], references: [cities.id] }), games: many(games) }));
export const gameFormatsRelations = relations(gameFormats, ({ many }) => ({ games: many(games) }));
export const gamesRelations = relations(games, ({ one, many }) => ({ host: one(user, { fields: [games.hostId], references: [user.id], relationName: "games_host" }), club: one(clubs, { fields: [games.clubId], references: [clubs.id] }), format: one(gameFormats, { fields: [games.formatId], references: [gameFormats.id] }), players: many(gamePlayers), guests: many(gameGuests), circles: many(gameCircles) }));
export const gamePlayersRelations = relations(gamePlayers, ({ one }) => ({ game: one(games, { fields: [gamePlayers.gameId], references: [games.id] }), player: one(user, { fields: [gamePlayers.userId], references: [user.id], relationName: "game_players_user" }), inviter: one(user, { fields: [gamePlayers.invitedById], references: [user.id], relationName: "game_players_inviter" }) }));
export const circlesRelations = relations(circles, ({ one, many }) => ({ owner: one(user, { fields: [circles.ownerId], references: [user.id] }), members: many(circleMembers), games: many(gameCircles) }));
export const circleMembersRelations = relations(circleMembers, ({ one }) => ({ circle: one(circles, { fields: [circleMembers.circleId], references: [circles.id] }), member: one(user, { fields: [circleMembers.userId], references: [user.id] }) }));
export const gameCirclesRelations = relations(gameCircles, ({ one }) => ({ game: one(games, { fields: [gameCircles.gameId], references: [games.id] }), circle: one(circles, { fields: [gameCircles.circleId], references: [circles.id] }) }));
export const notificationRelations = relations(notifications, ({ one }) => ({ user: one(user, { fields: [notifications.userId], references: [user.id] }) }));
export const userBadgeRelations = relations(userBadges, ({ one }) => ({ user: one(user, { fields: [userBadges.userId], references: [user.id] }), badge: one(badges, { fields: [userBadges.badgeId], references: [badges.id] }) }));
export const trackingRelations = relations(userTracking, ({ one }) => ({ user: one(user, { fields: [userTracking.userId], references: [user.id] }) }));

export type User = typeof user.$inferSelect; export type NewUser = typeof user.$inferInsert;
export type Game = typeof games.$inferSelect; export type NewGame = typeof games.$inferInsert;
export type Circle = typeof circles.$inferSelect; export type AppNotification = typeof notifications.$inferSelect;
