import { createDatabase } from "./client";
import { badges, circleMembers, circles, cities, clubs, connectionRequests, gameCircles, gameFormats, gamePlayers, games, notificationPreferences, notifications, user, userBadges, userConnections, userTracking } from "./schema";

const cityData = [
  ["errachidia", "Errachidia", 31.9314, -4.4247], ["meknes", "Meknès", 33.8935, -5.5473], ["fes", "Fès", 34.0181, -5.0078],
  ["marrakech", "Marrakech", 31.6295, -7.9811], ["casablanca", "Casablanca", 33.5731, -7.5898], ["rabat", "Rabat", 34.0209, -6.8416],
  ["agadir", "Agadir", 30.4278, -9.5981], ["oujda", "Oujda", 34.6814, -1.9086], ["tanger", "Tanger", 35.7595, -5.8340],
] as const;
const names = ["Yassine Amrani", "Sara Bennani", "Hamza Alaoui", "Imane Idrissi", "Omar El Fassi", "Salma Tazi", "Ayoub Chraibi", "Nora Berrada", "Mehdi Lahlou", "Khadija Naciri", "Zakaria Skalli", "Lina Mansouri", "Anas Bakkali", "Meryem Filali", "Rachid Othmani"];
const now = new Date("2026-08-14T12:00:00.000Z");
const day = 86_400_000;
const at = (offset: number) => new Date(now.getTime() + offset * day);

export async function seed(url = process.env.DATABASE_URL ?? "file:./local.db") {
  const { client, db } = createDatabase({ url, ...(process.env.DATABASE_AUTH_TOKEN ? { authToken: process.env.DATABASE_AUTH_TOKEN } : {}) });
  await client.execute("PRAGMA foreign_keys = ON");
  const insert = async <T extends { id: string }>(table: Parameters<typeof db.insert>[0], values: T[]) => { await db.insert(table).values(values).onConflictDoNothing(); };

  await insert(cities, cityData.map(([key, name, latitude, longitude]) => ({ id: `city_${key}`, name, countryCode: "MA", latitude, longitude, googlePlaceId: `seed_place_${key}` })));
  await insert(clubs, cityData.flatMap(([key, cityName, latitude, longitude]) => [1, 2].map(n => ({ id: `club_${key}_${n}`, cityId: `city_${key}`, name: `${n === 1 ? "Arena" : "Stade"} ${cityName}`, address: `${n * 10}, avenue du Sport, ${cityName}`, latitude: latitude + n / 1000, longitude: longitude - n / 1000, googlePlaceId: `seed_club_${key}_${n}` }))));
  await insert(gameFormats, [["5v5", 5, 10], ["7v7", 7, 14], ["9v9", 9, 18], ["11v11", 11, 22]].map(([name, playersPerTeam, maxPlayers]) => ({ id: `format_${name}`, name: String(name), playersPerTeam: Number(playersPerTeam), maxPlayers: Number(maxPlayers), active: true })));
  await insert(user, names.map((name, i) => ({ id: `user_${String(i + 1).padStart(2, "0")}`, name, email: `joueur${i + 1}@example.test`, emailVerified: true, phoneNumberVerified: false, cityId: `city_${cityData[i % cityData.length]?.[0] ?? "rabat"}`, onboardingCompleted: true, profilePhotoStepCompleted: i % 3 !== 0, notificationPermissionAsked: true })));
  await insert(notificationPreferences, names.map((_, i) => ({ id: `pref_${i + 1}`, userId: `user_${String(i + 1).padStart(2, "0")}`, marketingEnabled: false })));
  await insert(userTracking, names.map((_, i) => ({ id: `tracking_${i + 1}`, userId: `user_${String(i + 1).padStart(2, "0")}`, gamesPlayed: i * 2, gamesHosted: Math.floor(i / 3) })));
  await insert(userConnections, [[1, 2], [1, 3], [2, 4], [3, 5], [6, 7], [8, 9]].map(([a, b], i) => ({ id: `friend_${i + 1}`, userOneId: `user_${String(a).padStart(2, "0")}`, userTwoId: `user_${String(b).padStart(2, "0")}` })));
  await insert(connectionRequests, [{ id: "request_1", senderId: "user_10", receiverId: "user_01", message: "On joue ensemble ?", status: "pending" as const }, { id: "request_2", senderId: "user_11", receiverId: "user_04", status: "rejected" as const }]);
  await insert(circles, [{ id: "circle_Atlas", ownerId: "user_01", name: "Lions de l'Atlas", description: "Matchs du week-end", privacy: "public" as const, shareCode: "ATLAS26" }, { id: "circle_medina", ownerId: "user_04", name: "Foot Medina", privacy: "private" as const, shareCode: "MEDINA7" }, { id: "circle_nord", ownerId: "user_08", name: "Joueurs du Nord", privacy: "public" as const, shareCode: "NORD11" }]);
  await insert(circleMembers, [{ id: "cm_1", circleId: "circle_Atlas", userId: "user_01", role: "owner" as const, status: "accepted" as const }, { id: "cm_2", circleId: "circle_Atlas", userId: "user_02", role: "admin" as const, status: "accepted" as const }, { id: "cm_3", circleId: "circle_Atlas", userId: "user_03", role: "member" as const, status: "accepted" as const }, { id: "cm_4", circleId: "circle_medina", userId: "user_04", role: "owner" as const, status: "accepted" as const }, { id: "cm_5", circleId: "circle_medina", userId: "user_05", role: "member" as const, status: "invited" as const }, { id: "cm_6", circleId: "circle_nord", userId: "user_08", role: "owner" as const, status: "accepted" as const }, { id: "cm_7", circleId: "circle_nord", userId: "user_09", role: "member" as const, status: "requested" as const }]);
  await insert(games, [{ id: "game_future", hostId: "user_01", clubId: "club_rabat_1", formatId: "format_7v7", date: at(7), price: 5000, currency: "MAD", status: "scheduled" as const, visibility: "public" as const, joinableAt: at(1), invitationCode: "FUTURE7" }, { id: "game_past", hostId: "user_04", clubId: "club_fes_1", formatId: "format_5v5", date: at(-7), price: 3000, currency: "MAD", status: "completed" as const, visibility: "friends" as const, invitationCode: "PAST005" }, { id: "game_cancelled", hostId: "user_08", clubId: "club_tanger_2", formatId: "format_11v11", date: at(3), price: 0, currency: "MAD", status: "cancelled" as const, visibility: "circles" as const, invitationCode: "CANCEL1", cancellationReason: "Terrain indisponible" }]);
  await insert(gamePlayers, [{ id: "gp_1", gameId: "game_future", userId: "user_01", status: "accepted" as const, source: "host" as const, isHost: true, joinedAt: now }, { id: "gp_2", gameId: "game_future", userId: "user_02", invitedById: "user_01", status: "accepted" as const, source: "invitation" as const, joinedAt: now }, { id: "gp_3", gameId: "game_future", userId: "user_03", invitedById: "user_01", status: "invited" as const, source: "invitation" as const }, { id: "gp_4", gameId: "game_future", userId: "user_05", status: "waiting" as const, source: "discovery" as const }, { id: "gp_5", gameId: "game_past", userId: "user_04", status: "accepted" as const, source: "host" as const, isHost: true, joinedAt: at(-10) }, { id: "gp_6", gameId: "game_past", userId: "user_06", status: "accepted" as const, source: "link" as const, joinedAt: at(-9) }, { id: "gp_7", gameId: "game_cancelled", userId: "user_08", status: "accepted" as const, source: "host" as const, isHost: true, joinedAt: now }]);
  await insert(gameCircles, [{ id: "gc_1", gameId: "game_cancelled", circleId: "circle_nord" }]);
  await insert(badges, [{ id: "badge_play_1", category: "games_played", threshold: 1, name: "Premier match", description: "Jouer son premier match", icon: "football" }, { id: "badge_play_10", category: "games_played", threshold: 10, name: "Titulaire", description: "Jouer 10 matchs", icon: "medal" }, { id: "badge_host_1", category: "games_hosted", threshold: 1, name: "Organisateur", description: "Organiser un match", icon: "whistle" }, { id: "badge_host_10", category: "games_hosted", threshold: 10, name: "Capitaine", description: "Organiser 10 matchs", icon: "captain" }]);
  await insert(userBadges, [{ id: "ub_1", userId: "user_01", badgeId: "badge_play_1", unlockedAt: at(-30) }, { id: "ub_2", userId: "user_04", badgeId: "badge_host_1", unlockedAt: at(-5) }]);
  await insert(notifications, [{ id: "notif_1", userId: "user_02", type: "game_invitation", payload: { gameId: "game_future" } }, { id: "notif_2", userId: "user_01", type: "connection_request", payload: { senderId: "user_10" }, readAt: now }, { id: "notif_3", userId: "user_04", type: "badge_unlocked", payload: { badgeId: "badge_host_1" } }]);
  client.close();
}

if (import.meta.url === `file://${process.argv[1]?.replaceAll("\\", "/")}`) await seed();
