import { Pressable, StyleSheet, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { theme } from "@/design-system";
import { AppText } from "./AppText";
export type Match = { time: string; format: string; venue: string; city: string; distance: string; players: string };
export function MatchCard({ match, featured = false }: { match: Match; featured?: boolean }) {
  if (featured) return <View style={styles.featured}><View style={styles.chips}><View style={styles.darkChip}><Ionicons name="navigate-outline" size={16} color={theme.colors.textInverse} /><AppText variant="labelSm" color="textInverse">À {match.distance}</AppText></View><View style={styles.warningChip}><Ionicons name="people-outline" size={16} color={theme.colors.textPrimary} /><AppText variant="labelSm">{match.players} joueurs</AppText></View></View><AppText variant="labelSm" color="primary" style={styles.center}>AUJOURD’HUI</AppText><AppText variant="displayXl" color="textInverse" style={styles.center}>{match.time}</AppText><AppText variant="labelSm" color="textInverse" style={styles.center}>{match.format.toUpperCase()}</AppText><AppText variant="headingSm" color="textInverse" style={styles.center}>{match.venue}</AppText><AppText variant="bodySm" color="primary" style={styles.center}>{match.city}</AppText><Pressable accessibilityRole="button" style={styles.cta}><AppText variant="actionMd">VOIR LE MATCH</AppText><Ionicons name="arrow-forward" size={22} color={theme.colors.textPrimary} /></Pressable></View>;
  return <Pressable accessibilityRole="button" style={styles.item}><View><AppText variant="headingLg">{match.time}</AppText><AppText variant="labelSm" color="primary">{match.format.toUpperCase()}</AppText></View><View style={styles.details}><AppText variant="headingSm">{match.venue}</AppText><AppText variant="bodySm" color="textSecondary">{match.city}</AppText><AppText variant="labelSm" color="primary">{match.distance} · {match.players}</AppText></View><Ionicons name="chevron-forward" size={20} color={theme.colors.textPrimary} /></Pressable>;
}
const styles = StyleSheet.create({ featured: { backgroundColor: theme.colors.surfaceBrand, borderRadius: theme.radius.lg, gap: theme.spacing.xs, padding: theme.spacing.md }, chips: { flexDirection: "row", justifyContent: "space-between" }, darkChip: { alignItems: "center", backgroundColor: theme.colors.textPrimary, borderRadius: theme.radius.full, flexDirection: "row", gap: 4, paddingHorizontal: 10, paddingVertical: 6 }, warningChip: { alignItems: "center", backgroundColor: theme.colors.warning, borderRadius: theme.radius.full, flexDirection: "row", gap: 4, paddingHorizontal: 10, paddingVertical: 6 }, center: { textAlign: "center" }, cta: { alignItems: "center", backgroundColor: theme.colors.primary, borderRadius: theme.radius.md, flexDirection: "row", justifyContent: "space-between", marginTop: theme.spacing.sm, minHeight: 48, paddingHorizontal: theme.spacing.md }, item: { alignItems: "center", backgroundColor: theme.colors.surface, borderColor: theme.colors.borderSubtle, borderRadius: theme.radius.md, borderWidth: 1, flexDirection: "row", gap: theme.spacing.md, minHeight: 86, padding: theme.spacing.md }, details: { flex: 1, gap: 2 } });

