import { useState } from "react";
import { router } from "expo-router";
import { Pressable, StyleSheet, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AppButton, AppHeader, AppText, AppTextInput, ProgressIndicator, ScreenContainer, ScreenTitle } from "@/components/ui";
import { theme } from "@/design-system";
const cities=["Errachidia","Meknès","Fès","Marrakech"];
export default function CityScreen(){const [selected,setSelected]=useState("Errachidia");const [query,setQuery]=useState("");const visible=cities.filter(city=>city.toLowerCase().includes(query.toLowerCase()));return <ScreenContainer footer={<AppButton label="Continuer" icon="arrow-forward" onPress={()=>router.push("/photo")}/>}><AppHeader/><ProgressIndicator step={2}/><ScreenTitle dark="Où" accent="jouez-vous ?" description="Sélectionnez votre ville pour trouver des joueurs près de chez vous."/><AppTextInput icon="search-outline" onChangeText={setQuery} placeholder="Rechercher une ville" value={query}/><View style={styles.list}>{visible.map(city=><Pressable accessibilityRole="radio" accessibilityState={{checked:selected===city}} key={city} onPress={()=>setSelected(city)} style={styles.row}><AppText>{city}</AppText><View style={[styles.radio,selected===city&&styles.selected]}>{selected===city?<View style={styles.radioInner}/>:null}</View></Pressable>)}</View><Pressable style={styles.location}><Ionicons name="location-outline" size={24} color={theme.colors.textPrimary}/><AppText>Utiliser ma position</AppText></Pressable></ScreenContainer>}
const styles=StyleSheet.create({list:{gap:theme.spacing.xs,marginTop:theme.spacing.sm},row:{alignItems:"center",backgroundColor:theme.colors.surface,borderColor:theme.colors.border,borderRadius:theme.radius.md,borderWidth:1,flexDirection:"row",justifyContent:"space-between",minHeight:48,paddingHorizontal:theme.spacing.md},radio:{borderColor:theme.colors.border,borderRadius:10,borderWidth:1,height:20,padding:4,width:20},selected:{backgroundColor:theme.colors.primary,borderColor:theme.colors.primary},radioInner:{backgroundColor:theme.colors.surface,borderRadius:4,flex:1},location:{alignItems:"center",borderColor:theme.colors.border,borderRadius:theme.radius.md,borderWidth:1,flexDirection:"row",gap:theme.spacing.sm,justifyContent:"center",marginTop:theme.spacing.lg,minHeight:48}});

